server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
#         uri: file:C:\\workspace\workspace_boot\usinsaWork\\git-repo
         uri: https://github.com/dsadsaddd1/USINSA.git
  application:
    name: config-service
    
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh